server:
    error:
        whitelabel:
            enabled: true

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/altiora?useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
    jpa:
        show-sql: true
        hibernate: 
            ddl-auto: update
            #naming:
                #implicit-strategy:  org.hibernate.cfg.ImprovedNamingStrategy
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect           